version: '3.8'

services:
  zabbix-server:
    image: ${ZABBIX_SERVER_IMAGE:-zabbix/zabbix-server-pgsql:ubuntu-7.2.9}
    container_name: zabbix-server
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-zabbix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zabbix}
      POSTGRES_DB: ${POSTGRES_DB:-zabbix}
      TZ: ${TZ}
    depends_on:
      - postgres
    networks:
      - network-zabbix

  zabbix-frontend:
    image: ${ZABBIX_FRONTEND_IMAGE:-zabbix/zabbix-web-nginx-pgsql:ubuntu-7.2.9}
    container_name: zabbix-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-zabbix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zabbix}
      POSTGRES_DB: ${POSTGRES_DB:-zabbix}
      PHP_TZ: ${TZ}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
    depends_on:
      - zabbix-server
    networks:
      - network-zabbix

  zabbix-agent:
    image: ${ZABBIX_AGENT_IMAGE:-zabbix/zabbix-agent2:ubuntu-7.2.9}
    container_name: zabbix-agent
    restart: unless-stopped
    ports:
      - "10050:10050"
    environment:
      ZBX_ACTIVE_ALLOW: false
      TZ: ${TZ}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: zabbix-agent
      ZBX_HOSTNAMEITEM: system.hostname
    depends_on:
      - zabbix-server
    networks:
      - network-zabbix

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:16.2-alpine}
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-zabbix}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-zabbix}
      POSTGRES_DB: ${POSTGRES_DB:-zabbix}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TZ}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-zabbix}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network-zabbix

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:12.0.0}
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD:-strongpassword}
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      TZ: ${TZ}
    user: "472"
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - zabbix-frontend
    networks:
      - network-zabbix

volumes:
  postgres: {}
  grafana: {}

networks:
  network-zabbix:
    driver: bridge
